### ISSUE TITLE
Hi I went to Peckham and got stabbend.

### ISSUE THREAD

**Issue by Print-Spectro** [jacklqiu/shank-detector#1]
Hi I went to Peckham and got stabbend. I am not a professional user however. Could you make a non-pro version for non-professional users so I can go to places like Peckhamplex cinema without a trip to hospital afterwards? Much appreciated.

**Comment by kevcen** [comment]
hi, unfortunately SHANK PROOF FREE is not on the current horizons of our roadmap. we recommend you to call 111 and get an ambulance if you have been stabbend
